rk4: rk4.o
	c++ -o rk4 rk4.o -ltrapfpe -lpgplot -lcpgplot -lX11 -lm 

rk4.o: rk4.cpp
	c++ -c rk4.cpp

rk4: rk4.o
	c++ -o rk4 rk4.o -ltrapfpe -lpgplot -lcpgplot -lX11 -lm 

rk4.o: rk4.cpp
	c++ -c rk4.cpp

plot2pages: plot2pages.o
	c++ -o plot2pages plot2pages.o -ltrapfpe -lpgplot -lcpgplot -lX11 -lm 

plot2pages.o: plot2pages.cpp
	c++ -c plot2pages.cpp




