finite: finite.o
	c++ -o finite finite.o -ltrapfpe -lpgplot -lcpgplot -lX11 -lm 

finite.o: finite.cpp
	c++ -c finite.cpp

finite: finite.o
	c++ -o finite finite.o -ltrapfpe -lpgplot -lcpgplot -lX11 -lm 

finite.o: finite.cpp
	c++ -c finite.cpp

plot2pages: plot2pages.o
	c++ -o plot2pages plot2pages.o -ltrapfpe -lpgplot -lcpgplot -lX11 -lm 

plot2pages.o: plot2pages.cpp
	c++ -c plot2pages.cpp




